### ISSUE TITLE
WEBSITE: Add linting of markdown

### ISSUE THREAD

**Issue by azinit** [feature-sliced/documentation#108]
> Надзадача: #104

- [ ] Пройтись форматированием
- [ ] Добавить CI проверки
- [ ] Указать необходимые экстеншены

В связи с тем, что скорее всего потом будет юзать экстеншены и возможно даже CI проверки
![image](https://user-images.githubusercontent.com/42924400/117141864-b4456800-adb7-11eb-948e-659e7ab2ed9b.png)

> [Идея](https://github.com/feature-sliced/wiki/blob/fc2dbde5e8fa4e211a3f788495f36e0ab137bc61/.vscode/readme.md) - от @karina-jovian

**Comment by sarmong** [comment]
Мне кажется, не стоит привзяываться к плагину вскода. 

Prettier из коробки форматирует маркдаун.

**Comment by Krakazybik** [comment]
> Мне кажется, не стоит привзяываться к плагину вскода.

Почему к плагину? [тыц](https://github.com/DavidAnson/markdownlint)

**Comment by sarmong** [comment]
На мой взгляд, хорошая практика разделять линтер и форматтер в js коде. Линтер отвечает чисто за стиль и конвенции, а форматтер - за, эм, форматирование. Возможно, это же стоит делать и с маркдауном

**Comment by azinit** [comment]
> Мне кажется, не стоит привзяываться к плагину вскода.

Привязываться и **не обязательно**, но можно указать для улучшения взаимодействия в докой 🤔 

При этом такое должно линтиться по-хорошему, поэтому мб получится разрулить на уровне линта/преттира

> Prettier под капотом использует remark. Думаю, можно его и напрямую подключать.

Да, надо бы глянуть)
Просто тут еще сам md на валидность надо проверять (во многом по инициативе от @RinAkaia)

Поэтому возможно лучше посмотреть все же в сторону eslint, чтобы и в CI лучше было бы заложить сразу
(чтобы не обязательно было экстеншен ставить)

**Comment by sarmong** [comment]
>Поэтому возможно лучше посмотреть все же в сторону eslint, чтобы и в CI лучше было бы заложить сразу
В CI можно и prettier, и remark поставить

**Comment by azinit** [comment]
> В CI можно и prettier, и remark поставить

Да я понимаю, не стал это уточнять уж)

Тут же в целом еще речь про то - что в prettier вряд ли вшиты правила "валидации" md, помимо форматирования

А в этом пропозале имено это было важно

@RinAkaia надеюсь подскажет что-нить еще

**Comment by RinAkaia** [comment]
> @RinAkaia что думаешь по этому всему?

Не уверена, что с форматтэром у нас не поломаются те места, где приходится использовать сторонний синтаксис для docusaurus

Мне кажется сейчас главное линтинг поднять, а остальное уже только в экспериментальном режиме

**Comment by illright** [comment]
Not a priority
