### ISSUE TITLE
WEBSITE: Добавить более строгий линтинг и проверку на EOL

### ISSUE THREAD

**Issue by azinit** [feature-sliced/documentation#141]
Чтобы [такой фигни](https://github.com/feature-sliced/documentation/pull/140/commits/0a2e47fb07cc0ae73a1ad53e48aa5df8e959e377) не возникало

![image](https://user-images.githubusercontent.com/42924400/125175716-79581a00-e1d6-11eb-96fb-4cb06aa8411b.png)

**Comment by illright** [comment]
Not a priority due to lack of contributors, and for the current contributors this is not a problem. Besides, that's what Prettier does
