### ISSUE TITLE
WORKFLOW: Добавить css-препроцессор

### ISSUE THREAD

**Issue by azinit** [feature-sliced/documentation#142]
А то щас прям печаль беда с этим =(

![image](https://user-images.githubusercontent.com/42924400/125192670-be6d6200-e251-11eb-991a-77c6daeb4615.png)

![image](https://user-images.githubusercontent.com/42924400/125192696-e1981180-e251-11eb-83dc-7c68ec8c6a48.png)

**Comment by tednaaa** [comment]
могу взять задачу на себя и попробовать в след. выходные зарефакторить все стили под scss

**Comment by azinit** [comment]
Круть, по всем вопросам - пингуй меня прям тут или в лс)
