### ISSUE TITLE
FEEDBACK: Проработать возможность получения фидбека по каждой статье

### ISSUE THREAD

**Issue by azinit** [feature-sliced/documentation#153]
- Добавить возможность получать фидбек по конкретной доке (Помогло/Не помогло?)
- Возможно прикрутить метрику

**Comment by martis-git** [comment]
![image](https://user-images.githubusercontent.com/42924400/127038425-f8400bf1-77cf-42a1-886c-9cfad0576122.png)

**Comment by azinit** [comment]
Уже сделано по #276
