### ISSUE TITLE
Адаптировать вставки из Clean Architecture (с референсом)

### ISSUE THREAD

**Issue by azinit** [feature-sliced/documentation#155]
> Возможно пойдет в статью по сравнению с `Clean Architecture`

**Статья:** https://habr.com/ru/company/mobileup/blog/335382/

![image](https://user-images.githubusercontent.com/42924400/127034955-59b29dee-c0e9-468c-998b-adf4727e32ec.png)
![image](https://user-images.githubusercontent.com/42924400/127034961-bd8b2fe2-d00f-4598-852b-e95cb5a3cec6.png)
![image](https://user-images.githubusercontent.com/42924400/127034967-4bd2bf05-be58-43ba-aafd-ac1a20dfa774.png)
![image](https://user-images.githubusercontent.com/42924400/127034984-f5f73ad1-43e5-46b0-8454-7873b1fb7faf.png)
![image](https://user-images.githubusercontent.com/42924400/127034991-7ac58dc5-484c-4243-a773-545be64bb527.png)
![image](https://user-images.githubusercontent.com/42924400/127034998-0e59c28d-8e0a-4ee3-9b6c-69560038bba8.png)
![image](https://user-images.githubusercontent.com/42924400/127035016-5adffb59-3143-49bb-8a8f-fad9ed07b3d1.png)
![image](https://user-images.githubusercontent.com/42924400/127035024-4ad0f78b-f261-4710-95c7-cdd45fc303c3.png)

**Comment by martis-git** [comment]
![image](https://user-images.githubusercontent.com/42924400/127035192-607197db-7e5a-48b6-bdb7-f9c759fe9f75.png)

**Comment by azinit** [comment]
Будет сделано по тикету:

https://github.com/feature-sliced/documentation/issues/165
