### ISSUE TITLE
EDITING: Find more correct translation (RU)

### ISSUE THREAD

**Issue by azinit** [feature-sliced/documentation#157]
https://feature-sliced.design/docs/guides/low-coupling/
https://github.com/feature-sliced/documentation/pull/120#discussion_r632971266

![image](https://user-images.githubusercontent.com/42924400/127036909-82f3b1b6-648a-4f1d-a31e-8fb8855e4e02.png)

**Comment by GhostMayor** [comment]
Слабая связанность и Сильная сплоченность

**Comment by azinit** [comment]
@GhostMayor 🤷‍♂️ 

![image](https://user-images.githubusercontent.com/42924400/129461926-a262ab96-bc42-4c7b-9ad7-a3c34abb08ac.png)
![image](https://user-images.githubusercontent.com/42924400/129461939-47927d11-8707-4f2f-9549-d50224b68e8a.png)
![image](https://user-images.githubusercontent.com/42924400/129461941-d1837e34-f2fc-424d-9753-cd9862a55edf.png)
![image](https://user-images.githubusercontent.com/42924400/129461943-2c5592f0-fcf8-4443-a98e-3c5aa7079e59.png)

**Comment by GhostMayor** [comment]
Ну если так то можно не дословно переводить (пример Ghost in the Shell - можно перевсти как призрак в ракушке) 

К примеру Слабо зависимы но Сильно связаны

**Comment by azinit** [comment]
В том и проблема - что нужен компромисс разумный)

Возможно есть альтернативные точки зрения по вопросу, но пока кажется, что остаются варианты:

- "Low Coupling" - низкая **внешняя связность**
- "High Cohesion" - высокая **внутренняя связность**

**Comment by azinit** [comment]
> но все же внешнаяя - это не связность, лучше уж связанность. 

![image](https://user-images.githubusercontent.com/42924400/147024020-7587dff4-c320-43e5-9c4d-5a37644dc2df.png)

**Comment by azinit** [comment]
Ну как будто да, лучше прям так в доке и указать, за неимением более лучших вариантов

Пройтись по основным статьям:
https://feature-sliced.design/docs/concepts/low-coupling
https://feature-sliced.design/docs/concepts/cross-communication

И пройтись по всей доке в целом, где встречаются слова `зацепленность`, `связность`, `связанность`

**Comment by azinit** [comment]
https://ota-solid.vercel.app/dip

![image](https://user-images.githubusercontent.com/42924400/152930602-47f3f24c-9627-4ff8-bbfb-111aa75bb0ca.png)
