### ISSUE TITLE
Добавить community-preview для страниц документации (+ проработать meta)

### ISSUE THREAD

**Issue by azinit** [feature-sliced/documentation#164]
https://www.apollographql.com/docs/react/

![image](https://user-images.githubusercontent.com/42924400/127041088-f248f348-a224-48e5-a877-4bfdb7aa9dc3.png)

**Comment by martis-git** [comment]
- https://postkit.co/?ref=producthunt
- https://github.com/micheleriva/gauguin
- https://css-tricks.com/auto-generated-social-media-images/
- https://cards.microlink.io/

**Comment by azinit** [comment]
Если указывать ссыль в соц сетях, то тож изображение сайта не отображается в мете)

**Comment by azinit** [comment]
Примеры

https://github.com/wokwi/wokwi-docs/blob/099252303c4a578dc846e840900e6cf0f242199c/docusaurus.config.js
https://github.com/Franzininho/docs-franzininho-site/blob/9530bf3e9223e9b9b9aac4dcb86443f9daa6a26e/docusaurus.config.js
https://github.com/search?l=&q=og%3Aimage+filename%3Adocusaurus.config.js&type=code
https://github.com/facebook/react-native-website/blob/master/website/docusaurus.config.js
https://github.com/leon-ai/docs.getleon.ai/tree/master
