### ISSUE TITLE
DISCOVERY: (QUICK-PROMO) Adapt "layered-cake" scheme

### ISSUE THREAD

**Issue by azinit** [feature-sliced/documentation#178]
## Problem

This "cake scheme" was only draft of idea about "layered" project architecture.

But at the moment it's clear that we need to upgrade to more actual an complete state

## Requirements
- [ ] There is on scheme **must be showed:**
   - Main [layers](https://feature-sliced.design/en/docs/reference/layers/overview) from methodology (`shared`, `features`, `pages`, `app`)
   - Main [segments](https://feature-sliced.design/en/docs/reference/segments) from methodology (`ui`, `model`, `lib`, `api`)
   - "Sliced" conception with decomposing "smth big" by "self-contained parts"
   
- [ ] It would be cool, if we could display a set of core-concepts our methodology:
   - `Layered`
   - `Cake `(as main emojii-association 🍰 )
   - `Parts & Compose` (🧩)
   - `Sliced`
   - `Segments`

## References

Unfortunately, without any sources :(

![image](https://user-images.githubusercontent.com/42924400/127044659-bcb62514-03ab-4d30-bf2f-468b0b274e8d.png)
![image](https://user-images.githubusercontent.com/42924400/127048663-feb53029-d149-4807-b8f8-a0de4e453fa4.png)
![image](https://user-images.githubusercontent.com/42924400/139154089-d45a4636-c272-4dd2-95cd-962c4e75f82a.png)
![image](https://user-images.githubusercontent.com/42924400/139154095-3208d61e-891b-469b-b39a-222d751ca87e.png)
![image](https://user-images.githubusercontent.com/42924400/139154111-8c8d220e-d8f9-45a9-b39a-cc780e4b1ebb.png)
![image](https://user-images.githubusercontent.com/42924400/139154139-0983d7de-73ef-4a59-ab88-1b283b634da3.png)

**Comment by martis-git** [comment]
Возможно добавить больше акцента на "слайсинге"

![image](https://user-images.githubusercontent.com/42924400/127048663-feb53029-d149-4807-b8f8-a0de4e453fa4.png)

**Comment by Postamentovich** [comment]
👍

**Comment by Postamentovich** [comment]
![DIAGRAM-01](https://user-images.githubusercontent.com/22918007/150944774-42160c6c-e9b5-4fc9-8b3a-ffcb5997b734.svg)

**Comment by azinit** [comment]
@illright Мб поделишься мнением, как лучше схему слоистую адаптировать? 🤔

**Comment by illright** [comment]
Возможно, стоит убрать из слоистой диаграммы названия непосредственных слоев (потому что их всех все равно не уместить), и сделать эту диаграмму "анатомией слоя". Еще одна причина так поступить – эта диаграмма, как и скриншот структуры директорий, немного абстрактна и отсоединена от реальных интерфейсов. Из-за этого мне кажется, что она не так полезна для понимания методологии в целом. Она полезна для понимания вложенности понятий.

Если подытожить – мне кажется, что на странице введения стоит поместить интерактивную диаграмму, объясняющую слои, а также слоистую диаграмму без названий конкретных слоев в раздел Анатомия.

**Comment by illright** [comment]
Насчет диаграммы, которую @Postamentovich вкинул – во-первых, лайк, очень лаконично и современно. Во-вторых, вижу, что помимо объяснения анатомии слоя и демонстрации порядка слоев (пусть и неполного) там есть еще один "дата-поинт" – отличие слоя Shared от остальных слоев. Это полезная информация, но я не уверен, что на этой диаграмме она получает должное количество внимания. Возможно, эту информацию будет проще донести текстом в описании слоя Shared.

И насчет того, как нарисован слой Shared – у меня создается впечатление, что слой Shared состоит из слайсов, но по факту он ведь должен состоять из сегментов? Может быть, если оставлять этот слой на диаграмме, лучше будет нарисовать не круг, поделенный на 4 сектора, а концентричные круги разного диаметра?

**Comment by illright** [comment]
Ну и еще можно подумать о том, чтоб добавить на диаграмму цвета. Создать общепринятый колор-кодинг слоев, и отразить его в диаграмме.

**Comment by illright** [comment]
Еще момент. Для русской версии документации нужны русские пометки на диаграмме. Обратил на это внимание, пока пытался очистить доку от ссылок. Пусть будет "слой", "слайс", "сегмент". Названия слоев и сегментов можно оставить на английском. Если названия будут на английском, будет немало путаницы и проблем с формулировками на странице Введение.

Еще на последней версии диаграммы **layers** хорошо бы сменить на единственное число.

**Comment by azinit** [comment]
> Еще момент. Для русской версии документации нужны русские пометки на диаграмме. Обратил на это внимание, пока пытался очистить доку от ссылок. Пусть будет "слой", "слайс", "сегмент". Названия слоев и сегментов можно оставить на английском. Если названия будут на английском, будет немало путаницы и проблем с формулировками на странице Введение.

Кажется, проблема более глобальная, и связана с локализацией)
И если выбирать между
1) Хранить и поддерживать по две версии под каждую локаль
2) Хранить одну версию, но использовать ее везде (english-first)

То кортима склоняется все же ко второму варианту
Т.к. под каждый язык не адаптируешься)
(и даже если адаптируешься - то потом это дело еще поддерживать надо, что проблемней)

https://github.com/feature-sliced/documentation/issues/243
