### ISSUE TITLE
DISCOVERY: Решить вопрос с кириллицей в url-anchors

### ISSUE THREAD

**Issue by azinit** [feature-sliced/documentation#189]
- [Выглядит как решение](https://github.com/facebook/docusaurus/blob/master/website/docs/introduction.md#fast-track-%EF%B8%8F-fast-track) но посмотреть все возможные альтернативы

- При этом лучше заменить все на латиницу , чтобы для всех локалей были единые ссылки (@unordinarity @kara-jovian FYI)

![image](https://user-images.githubusercontent.com/42924400/127049091-9dd54f02-54e6-41aa-ae67-a2930dfd8c62.png)

**Comment by martis-git** [comment]
и не забывать про то, что долно быть совместимо при i18n

**Comment by martis-git** [comment]
![image](https://user-images.githubusercontent.com/42924400/127049190-623647a6-5d03-480b-95ee-0c737203695a.png)

**Comment by martis-git** [comment]
Возможно стоит транслитить сразу, если не латиница 🤷‍♂️

**Comment by azinit** [comment]
Важно поскорей влить, т.к. если при код-ревью кидать ссылки на секции статей, то кириллица плохо отображается(

Надо бы улучшить сценарий шаринга и референса на наши статьи
