### ISSUE TITLE
FIX typos

### ISSUE THREAD

**Issue by azinit** [feature-sliced/documentation#195]

**Comment by martis-git** [comment]
![image](https://user-images.githubusercontent.com/42924400/127051510-bd8b6927-ee56-44ce-a23b-8d5268a716b6.png)

**Comment by martis-git** [comment]
![image](https://user-images.githubusercontent.com/42924400/127054357-904c7c29-c429-4917-adae-696e3288b3f1.png)

**Comment by martis-git** [comment]
![image](https://user-images.githubusercontent.com/42924400/127054383-63da7d2d-05ac-4d60-8aee-10aaded99c3a.png)

**Comment by martis-git** [comment]
Сделать менее радикальной формулировку

![image](https://user-images.githubusercontent.com/42924400/127057316-2062b43a-3fdb-464d-98dc-34715495c427.png)

**Comment by martis-git** [comment]
"на слое" => "в слое"

![image](https://user-images.githubusercontent.com/42924400/127057381-7f5c9450-d461-4fe5-b95c-f657a70f7c60.png)
