### ISSUE TITLE
Пофиксить admonitions на сайте

### ISSUE THREAD

**Issue by azinit** [feature-sliced/documentation#208]
Предложение от @GhostMayor:

```
просто странно что для темной темы, они не делают чтобы все было притонено в темный и белым текстом везде
```

**Ожидаемый (примерно) результат:**
![image](https://user-images.githubusercontent.com/42924400/127054692-c891bb40-0ae7-4819-9687-00dbf4aa7d70.png)

**Comment by martis-git** [comment]
То как сейчас - немного уныленько

![image](https://user-images.githubusercontent.com/42924400/127060136-5c79803d-490c-4bb9-bf6d-5b1e0350f82a.png)


Но и у редакса полностью перенимать пробовали - тож не айс

![image](https://user-images.githubusercontent.com/42924400/127060109-2b400a51-12d0-4cdc-b0c8-586987f90c0a.png)

**Comment by azinit** [comment]
В 2.0.0-beta.4 уже нормальные admonitions юзаются

@feature-sliced/core мб обновимся? 🤔 

https://docusaurus.io/docs/i18n/git
![image](https://user-images.githubusercontent.com/42924400/130483232-18183c47-c7ec-44ba-8840-5887f0f6b16d.png)
