### ISSUE TITLE
FEEDBACK: Адаптировать FeatureDriven концепции к фиче-слайсам

### ISSUE THREAD

**Issue by azinit** [feature-sliced/documentation#219]
А конкретно - как они проявляют себя в новой версии методологии

https://github.com/feature-sliced/documentation/tree/rc/feature-driven#concepts

![image](https://user-images.githubusercontent.com/42924400/127059653-993f6952-bf76-40aa-956f-bd72628be5b1.png)

**Comment by martis-git** [comment]
![image](https://user-images.githubusercontent.com/42924400/127059767-73229805-c68e-4235-a242-1364a8864a2e.png)

**Comment by illright** [comment]
Seems like all the benefits of FD are already present in FSD in one way or another, I don't think this needs a special mention in the docs
