### ISSUE TITLE
HOWTO: Добавить гайд по работе с NextJS

### ISSUE THREAD

**Issue by azinit** [feature-sliced/documentation#225]
- [ ] Адаптировать конфликт с pages
- [ ] Выявить другие конфликты
- [ ] Описать решения в гайде

**Comment by vladislavromanov** [comment]
В NextJS появилась возможность [складывать компоненты в папку pages](https://nextjs.org/docs/api-reference/next.config.js/custom-page-extensions#including-non-page-files-in-the-pages-directory). 

Нужно добавить в `nextjs.config.js` поле `pageExtensions`:

```js
module.exports = {
  pageExtensions: ['page.tsx', 'page.ts', 'page.jsx', 'page.js'],
}
```

Так страницами будут считаться только файлы, которые заканчиваются на .page.tsx.

**Comment by skaneprime** [comment]
bump! Надеюсь вы не забросили затею с Next.JS ? А то там добавили всякого!

**Comment by djnsu** [comment]
текущая версия методолгии не вписывается в новую фичу app directory от Next JS 13

**Comment by illright** [comment]
Для всех интересующихся, гайд был добавлен — https://feature-sliced.design/ru/docs/guides/tech/with-nextjs

Там еще есть, что добавить, но это мы в дальнейшем улучшим
