### ISSUE TITLE
EDITING: Заменить термин «Антихрупкость» на «Устойчивость» по отношению к Public API

### ISSUE THREAD

**Issue by igorkamyshev** [feature-sliced/documentation#227]
В документации термин «антихрупкость» используется как синоним «прочность», «устойчивость», но оригинально он был введен Нассимом Талебом в книге «Антихрупкость» в смысле «получающий выгоду от воздействий».

> Талеб, вводя понятие «антихрупкость», сместил концептуальную направленность на способность выдерживать сильное воздействие или неожиданные события и на пользу от их возникновения.

> Антихрупкость не должна соотноситься с устойчивостью, понятой как способность противостоять негативным воздействиям. 

https://ru.wikipedia.org/wiki/Антихрупкость

Например, человеческие мышцы являются антихрупкими. Физические нагрузки приводят к увеличению запаса прочности и в следующий раз переживаются лучше.

Программные продукты, спроектированные по методологии feature-sliced не становятся лучше от внешних воздействий. Ни с точки зрения функциональных характеристик, ни с точки зрения качества кода. Они не являются антихрупкими.

Предлагаю исключить этот термин из документации и заменить его на «прочность» или «устойчивость», чтобы не вызывать ложных ассоциаций.

// душнила-мод отключен

**Comment by azinit** [comment]
Недавно тож эта мысль посещала, так что возможно действительно имеет смысл заменить на что-то более подобающее)

**Comment by azinit** [comment]
@igorkamyshev Мы помним! ✊
