### ISSUE TITLE
Помогите нам перевести feature-sliced / Help us translate feature-sliced

### ISSUE THREAD

**Issue by azinit** [feature-sliced/documentation#244]
> Памятка будет дополняться

Привет!)

На данный момент документация активно переводится на **английский язык**, в чем нам очень помогла бы ваша помощь! 🚀 

> 24.08.2021: Особенно учитывая, что на текущий момент это чисто машинный перевод

## Как можно помочь?

- Вычитывать EN-версию документации
  - Выписывать баги
  - Присылать PullRequests с исправлениями
- Предлагать улучшения / сервисы по инфраструктуре перевода (пока же используем чисто докузаурус)

## С чего начать исправление?

1. Предварительно изучить гайдлайны
   - [Docusaurus i18n tutorial ](https://docusaurus.io/docs/i18n/tutorial) (хотя бы базово)
   - [Contributing guidelines](https://github.com/feature-sliced/documentation/blob/master/CONTRIBUTING.md)

2. А дальше как обычно - форкаемся, вносим правки, прогоняем тесты (или ждем CI) и отправляем PR с изменениями на ревью (подробнее - в [contributing](https://github.com/feature-sliced/documentation/blob/master/CONTRIBUTING.md))

## Про что стоит помнить?

1. Версии документации для каждой локали располагаются рядом:
    * Документация (отдельные md-файлы со статьями)
      - RU: `website\i18n\ru\docusaurus-plugin-content-docs`
      - EN: `website\i18n\en\docusaurus-plugin-content-docs`
   * Общая локализация темы (json-словари)
     - RU: `website\i18n\ru\docusaurus-theme-classic`
     - EN: `website\i18n\en\docusaurus-theme-classic`

2. Если возникают сомнения касаемо перевода - смотрите изначальную версию на русском / английском
    - Особенно для JSON-словарей
 
3. Во всех случаях стоит поддерживать актуальные версии для всех локалей доки
    - Поэтому по возможности, если обновляете документацию, то либо обновите сразу ее в другой локали, или же выпишите [отдельную ишью](https://github.com/feature-sliced/documentation/issues/new)

4. Для запуска для определенной локали используйте команды
```bash
# website/README.md
$ yarn start        # for default locale
$ yarn start:ru     # for RU locale
$ yarn start:en     # for EN locale
```

> По всем вопросам по переводу обращаться к @kara-jovian @unordinarity или [в чат](https://t.me/feature_sliced)

**Comment by illright** [comment]
I think the translation is pretty good already, and pages where it isn't are due for a rewrite anyway
