### ISSUE TITLE
Поправить цвет кнопки на главной

### ISSUE THREAD

**Issue by azinit** [feature-sliced/documentation#261]
При переключении на темную тему, цвет текста должен оставаться белым (а не как на скрине)

Поломалось скорее всего после недавнего переезда на `docusaurus@2.0.0-beta.5`

![image](https://user-images.githubusercontent.com/42924400/131599558-343252e7-3ce4-4bf2-b68f-2532645e5ed4.png)

**Comment by websega** [comment]
Здесь есть несколько вариантов, как это исправить.

1. Переопределить переменную в :root, которая отвечает за цвет кнопки. Но это повлечет за собой изменение у всех кнопок с классом "button button--primary". Например, такая кнопка есть на станице с примерами ("Добавить пример")
2. Создать индивидуальный класс для этой кнопки, который будет использовать переменную с названием, например, "--home-button-color"

Какой из них предпочтительней?

**Comment by azinit** [comment]
Кажется, что для primary прям оптимально будет, если будет белый текст

![image](https://user-images.githubusercontent.com/42924400/135929441-511b6b17-0c3b-4f9b-a4a4-c28bd413479e.png)
![image](https://user-images.githubusercontent.com/42924400/135929448-2f2391f2-142d-4d27-8a34-674c37513bf0.png)
