### ISSUE TITLE
DISCOVERY: Restructure doc (completely, if needed)

### ISSUE THREAD

**Issue by azinit** [feature-sliced/documentation#298]
As at screen, **if needed**

https://illright.notion.site/illright/FSD-476df827ce5c4d0dae535cc5f7c97b30

![image](https://user-images.githubusercontent.com/42924400/155383358-f23cda29-4e99-46ed-bef6-480c5059af4a.png)

<details><summary>Old</summary>

![image](https://user-images.githubusercontent.com/42924400/137635743-c9e6113b-0526-46ea-9947-a314881fef8f.png)

</details>

**Comment by azinit** [comment]
![image](https://user-images.githubusercontent.com/42924400/140254540-1b74c02e-69ab-4951-97df-7f2933af3002.png)

**Comment by illright** [comment]
It's kind of how it is already
