### ISSUE TITLE
DISCOVERY: Add diataxis-type badges on articles

### ISSUE THREAD

**Issue by azinit** [feature-sliced/documentation#299]
- [ ] Diataxis-types adaptation: `Tutorial`, `Guide`, `Concept`, `Reference`
   ![image](https://user-images.githubusercontent.com/42924400/137637418-feebeb2b-8a02-4d2c-a59d-97f50a914626.png)
- [ ] Feel free to use color-/emojii highlighting
   - [ ] Like gatsby
     ![image](https://user-images.githubusercontent.com/42924400/137637461-e511cd5a-6449-4e84-b673-9ccb094e78ba.png)
 
- [ ] Feel free to use "built-in" docusaurus tags-styles
   ```html
   <span class="badge badge--primary">Primary text</span>
   <span class="badge badge--secondary">Secondary text</span>
   <span class="badge badge--success">Success text</span>
   <span class="badge badge--danger">Danger text</span>
   <span class="badge badge--warning">Warning text</span>
   <span class="badge badge--info">Info text</span>
   <span class="badge badge--light">Light text</span>
   <span class="badge badge--dark">Dark text</span>
   ```

**Comment by illright** [comment]
I'm not sure how these tags can be helpful to someone who's not familiar with Diataxis, which is our target audience
