### ISSUE TITLE
WEBSITE: Adapt scrollbar styles for Firefox

### ISSUE THREAD

**Issue by azinit** [feature-sliced/documentation#315]
## At Chrome (as expected)

![image](https://user-images.githubusercontent.com/42924400/139509538-0c7936b9-2aad-4ec7-97c4-54ff91c1c934.png)

## At Firefox (as actual)

![image](https://user-images.githubusercontent.com/42924400/139509568-67253687-9fe0-41eb-ba0d-70f4bf1e348b.png)

**Comment by Mihir50** [comment]
May I try this?

**Comment by azinit** [comment]
@Mihir50 Of course, any PR are welcome

_(there is only need to notify about it in the issue, yeap)_

**Comment by azinit** [comment]
For any questions - ping me

**Comment by azinit** [comment]
@Mihir50 Unfortunately, at the moment contributing guidelines and pr-template are only on RU lang 🤔

**Comment by Mihir50** [comment]
> @Mihir50 Unfortunately, at the moment contributing guidelines and pr-template are only on RU lang 🤔
> 
> Use translator

Yes

**Comment by Mihir50** [comment]
@azinit The only css scrollbar properties that firefox supports are scroll-width and scroll-color.  There is no css property to add border radius and color in the corners. Is this fine?
![Screenshot (98)](https://user-images.githubusercontent.com/58292449/139530738-f233668e-2bd7-40db-8d3b-7702b28f1936.png)

**Comment by azinit** [comment]
@Mihir50 Looks fine, but could you  please add more screenshots?

1) Firefox, Dark theme
2) Chrome, Dark and Light theme

**Comment by Mihir50** [comment]
@azinit 
Firefox dark:
![Screenshot (99)](https://user-images.githubusercontent.com/58292449/139532191-906d699e-e20c-460c-b8fb-1faa40b7b73f.png)

Chrome light:
![Screenshot (100)](https://user-images.githubusercontent.com/58292449/139532210-a64228f2-a528-42c9-85bc-f40c5f75fc47.png)

Chrome dark:
![Screenshot (101)](https://user-images.githubusercontent.com/58292449/139532215-a45c9cd1-3279-4bfd-8d6b-fc3b55a2664b.png)

**Comment by azinit** [comment]
@Mihir50 Hmm, looks fine)

The main _fear_ was that these styles will be conflicting

But if there are not another issues on your opinion, I think its time to prepare PR 🚀

**Comment by azinit** [comment]
Thanks for quick feedback and problem fixing 👍

**Comment by azinit** [comment]
> @Mihir50 JFYI, also you can select EN version
> ![image](https://user-images.githubusercontent.com/42924400/139532444-6c24f2fb-c233-4c09-b0cb-c184105c2f14.png)

**Comment by Mihir50** [comment]
> @Mihir50 Hmm, looks fine)
> 
> The main _fear_ was that these styles will be conflicting
> 
> But if there are not another issues on your opinion, I think its time to prepare PR rocket

One thing is that in firefox the color of the scroll-bar thumb changes when you hover or click to drag it

**Comment by azinit** [comment]
@Mihir50 Could you attach short screencast for demonstrating, please?

**Comment by Mihir50** [comment]
@azinit 

https://user-images.githubusercontent.com/58292449/139532789-da6934f5-9cc1-4548-a1d4-35d1e186a6cd.mp4

**Comment by azinit** [comment]
@Mihir50 On my opinion, it's even more "user-friendly" UX 😄 

I think we can keep this implementation with such behavior and prepare PR 🔥

**Comment by Mihir50** [comment]
Hey should I push the package-lock.json file as well?

**Comment by Mihir50** [comment]
Sorry If I am asking silly questions, but I am just a beginner in open-source

**Comment by azinit** [comment]
> Hey should I push the package-lock.json file as well?

I think no, because we use **yarn** as package manager)

![image](https://user-images.githubusercontent.com/42924400/139535270-cf82ec2e-f268-4243-bd47-1b91c5a33151.png)

> It's awesome how did you manage to launch project with npm 😄

**Comment by azinit** [comment]
@Mihir50 Anyway I suggest discussing any another issues/suggestions at PR

> Yeap, I see one from you 🚀

**Comment by Mihir50** [comment]
Okay. Thankyou for helping.

**Comment by Mihir50** [comment]
> > Hey should I push the package-lock.json file as well?
> 
> I think no, because we use **yarn** as package manager)
> 
> ![image](https://user-images.githubusercontent.com/42924400/139535270-cf82ec2e-f268-4243-bd47-1b91c5a33151.png)
> 
> > It's awesome how did you manage to launch project with npm smile

Even I don't know, I just ran npm start

**Comment by azinit** [comment]
> Even I don't know, I just ran npm start

Yeah, but should instead:

```sh
$ cd website // Change directory to "website/"
$ yarn // Install dependencies by Yarn
```

For this issue its not big problem, but JFYI)

**Comment by Mihir50** [comment]
> > Even I don't know, I just ran npm start
> 
> Yeah, but should instead:
> 
> ```shell
> $ cd website // Change directory to "website/"
> $ yarn // Install dependencies by Yarn
> ```
> 
> For this issue its not big problem, but JFYI)

Thankyou 👍

**Comment by azinit** [comment]
> Will my pull request get merged before 31st? because it needs to be counted for hacktoberfest😁

Sure)

**Comment by azinit** [comment]
@Mihir50 

![image](https://user-images.githubusercontent.com/42924400/139537855-a93d927a-ad46-41ee-88d3-1c8ac88f60ee.png)

**Comment by Mihir50** [comment]
> @Mihir50
> 
> ![image](https://user-images.githubusercontent.com/42924400/139537855-a93d927a-ad46-41ee-88d3-1c8ac88f60ee.png)

Thankyou very much 👍
