### ISSUE TITLE
WEBSITE: Add import aliases for @themes of Docusaurus

### ISSUE THREAD

**Issue by azinit** [feature-sliced/documentation#328]
For any questions - ping me

![image](https://user-images.githubusercontent.com/42924400/139595503-4e47c231-5ed1-4f81-94d8-ba94aa1f48cb.png)

**Comment by frkam** [comment]
@azinit is this issue actual? currently listed files doesn't has eslint-errors

**Comment by azinit** [comment]
@frkam Yeap, I suppose that we can close this issue as outdated
Thx for your attention!
