### ISSUE TITLE
EXAMPLE: TodoApp on VueJS

### ISSUE THREAD

**Issue by azinit** [feature-sliced/documentation#331]
## Description

Similar to TodoApp on React
https://github.com/feature-sliced/examples/tree/master/todo-app

More details
https://t.me/feature_sliced/5900

## Steps
- [x] Implement draft
   https://github.com/EliseyMartynov/fs-vue
- [x] **Review by CoreTeam**
   https://github.com/EliseyMartynov/fs-vue/discussions/2
- [x] **Review by VueJS expert (@niyazm524)**
   https://github.com/EliseyMartynov/fs-vue/discussions/2
- [x] Prepare and clean up repo
- [x] Add to global examples list

**Comment by magistrfox** [comment]
When I will have more free time I will definitely try to do something

**Comment by EliseyMartynov** [comment]
Current progress in this repo: https://github.com/EliseyMartynov/fs-vue

**Comment by azinit** [comment]
@EliseyMartynov ping me, when work will be finished 🤙

**Comment by azinit** [comment]
Review here: (in process...)
https://github.com/EliseyMartynov/fs-vue/issues/1

**Comment by azinit** [comment]
@EliseyMartynov Таки влили, йеее
Спасиб тебе большое!

Там пару багулек некрит остались, но уже то что есть - оч круто 🚀 
https://github.com/EliseyMartynov/fs-vue/issues/4
https://github.com/EliseyMartynov/fs-vue/issues/5
