### ISSUE TITLE
EXAMPLES: Add explicit selection of newest examples

### ISSUE THREAD

**Issue by azinit** [feature-sliced/documentation#365]
There is problem to notice recently updated examples in common examples list.

- [ ] As solution idea - to define explicitly field `updatedAt` at config of examples. And then render badge "NEW" if there is passed less than 2 weeks (as example)

![image](https://user-images.githubusercontent.com/42924400/142263183-63e64c15-72bb-4c99-9253-8777a6c7175f.png)

**Comment by tednaaa** [comment]
Могу взять на себя задачку
