### ISSUE TITLE
EDITING: Clean up "Intro" section

### ISSUE THREAD

**Issue by azinit** [feature-sliced/documentation#420]
Clean up base issues in "Intro" section

https://feature-sliced.design/docs/intro

### Subtasks
- [x] #421
- [x] #423
- [x] #422
- [x] #439
- [x] #440
- [x] #441
- [x] #442
- [x] #444
- [ ] #445
- [x] #474

### References

Discussion https://github.com/feature-sliced/documentation/discussions/411
Blocks #335

**Comment by illright** [comment]
I think we should also add tasks for checking the text of the page with [Glavred](https://glvrd.ru/) (ru), [LanguageTool](https://languagetool.org/ru/) (ru) and [Grammarly](https://www.grammarly.com/) (en).

**Comment by azinit** [comment]
@illright Если будут какие вопросы по пунктам - дай знать 🤔
