### ISSUE TITLE
EDITING(INTRO): Actualize NavCards "Table Of Contents"

### ISSUE THREAD

**Issue by azinit** [feature-sliced/documentation#445]
## Проблема

Нав.карточки сейчас [достаточно спорны](https://github.com/feature-sliced/documentation/pull/432#pullrequestreview-868900819) по реализации, т.к. не выполняют главной задачи - "прозрачно навигировать по контенту"

Где-то этому мешают предшествующие ссылки в Intro, где-то громкие тайтлы, где-то общий формат карточек

Хочется адаптировать NavCardsMenu из Intro под текущую доку, чтоб приводило **к нужным статьям и не внушало ложных надежд**

## Комментарий

@illright , после предыдущих ишьюсов возможно поправишь уже параллельно

В таком случае - просто закрой задачу к тому моменту
(но лучше отдельным PR, чтоб не затягивалось)

**Comment by azinit** [comment]
@illright вродь как договорились оставить только IndexPage без путанницы
Тогда задачка вроде неактуальной становится

Или поправишь попозж как посчитаешь нужным?

**Comment by illright** [comment]
I think this is no longer relevant
