### ISSUE TITLE
EDITING: (LINKS) Remove redundant and confusing links

### ISSUE THREAD

**Issue by azinit** [feature-sliced/documentation#452]
## Description

Links in docs confuse users

There are a few reasons:
- Some links lead "nowhere"
   (For a link, it is important not only where it leads, but also from where, so that when you click on it, it is clear which information gap this link fills.)
- Some links interfere for reading article
   (Them confuse users during reading)

The main goal is to remove links without losing navigation and documentation quality

## Subtasks

Decompose for other articles/sections as you need

- [ ] #432

**Comment by illright** [comment]
This ticket is too broad to be taken into work, if we find pages with this problem, we should make separate tickets for each one.
