### ISSUE TITLE
DISCOVERY: (QUICK-PROMO) Actualize "Layered" scheme

### ISSUE THREAD

**Issue by azinit** [feature-sliced/documentation#480]
## Подзадачи

- [ ] Заменить схему на лендинге на более актуальную (из Intro, лучше взять сразу англ версию)
- [ ] Адаптировать по необходимости стили для корректного отображения в светлой и темной темах

## Проблема

Старая слоистая схема [сильно потеряла в актуальности](https://github.com/feature-sliced/documentation/discussions/411#discussioncomment-2020963), и нуждается в замене [на полноценную интерактивную диаграмму](https://user-images.githubusercontent.com/42924400/150945014-9c3ab930-404f-4c28-8341-8719a4f9e998.mp4)

На время разработки самой интерактивной диаграмы, надо бы заменить на хотя бы какую-нибудь версию поактуальней

<table>
<td>

Как сейчас
![image](https://user-images.githubusercontent.com/42924400/159806577-6c247eb7-9a5c-4fc5-8957-7dab65165da9.png)

</td>
<td>

Как хотелось бы 
![image](https://user-images.githubusercontent.com/42924400/159806975-81271ca3-9941-4ae7-9824-ffd067540b29.png)

</td>
</table>

**Comment by azinit** [comment]
@RinAkaia JFYI

**Comment by illright** [comment]
Кажется, эта задача решена

**Comment by azinit** [comment]
@illright Пока да, но там еще хотелось бы улучшить текущую + интерактивную диаграмку запилить
Но это тогда уже по #178 допилим
