### ISSUE TITLE
QUESTION: Difference between processes and features?

### ISSUE THREAD

**Issue by enzzoperez** [feature-sliced/documentation#488]
Hi!, Im not sure if Im understood this difference well, because features can group other features and processes group pages, an example says `Transfer of funds between accounts[​](https://feature-sliced.design/en/docs/reference/layers/features#transfer-of-funds-between-accounts)`, but I see transfer of funds as a `process` since I'll need some pages to finish a transfer.

Could you explain this with a example a little more clear please?

Thanks for docs!

**Comment by azinit** [comment]
@feature-sliced/core

**Comment by azinit** [comment]
@enzzoperez Hello!
CoreTeam at the moment is overloaded, but also recommend to repeat question at our chat:
https://t.me/feature_sliced

**Comment by illright** [comment]
In case this question hasn't been answered in the chat yet: the processes layer has been, as of recently, deprecated. The difference between processes and features was unclear even to the core team members, so we decided that the role of the processes layer is sufficiently fulfilled by existing layers like Features and App.

If you're using Processes in your projects, feel free to move most of this functionality to Features. If you need to work around the import rule on layers, move some parts to App.

Feel free to open another issue if the migration process is unclear, or ask for help in one of our communities!
