### ISSUE TITLE
Вопрос по сегменту ui

### ISSUE THREAD

**Issue by WoodenPC** [feature-sliced/documentation#518]
Привет, возник вопрос по папке ui внутри слайса фичи/виджета . Проект на react + effector. Исходя из описания методологии, кажется, что внутри любого компонента, который лежит в `feature/ui` мы можем коннектиться к стору. Стал замечать, что у меня появляется микс компонентов внутри `feature/ui`, часть коннектиться к стору, а часть нет.  И те компоненты, что не коннектятся к стору, в `entity` не засунешь, т.к. они в основном появляются из-за какой то сложной верстки, которую выносим в отдельный компонент, и этот новый компонент переиспользуется между файлами в `feature/ui`. Появляется навязчивая мысль разделять `ui` и `ui-components`, что очень похоже на  `containers/components`, чего очень не хотелось бы делать.  Методология как то регламентирует такие моменты ? Или это норма ?

**Comment by AlexandrHoroshih** [comment]
Привет!

Нет, методология [никак не регулирует структуру ui-сегмента, только содержимое](https://feature-sliced.design/docs/reference/segments#ui)
Внутри допустимо использовать и свою структуру, и условный atomic-design

**Comment by azinit** [comment]
> Стал замечать, что у меня появляется микс компонентов внутри feature/ui, часть коннектиться к стору, а часть нет. И те компоненты, что не коннектятся к стору, в entity не засунешь, т.к. они в основном появляются из-за какой то сложной верстки, которую выносим в отдельный компонент, и этот новый компонент переиспользуется между файлами в feature/ui. Появляется навязчивая мысль разделять ui и ui-components, что очень похоже на containers/components, чего очень не хотелось бы делать

Плюс добавил бы, что "коннектинг" к стору - не единственная мера абстрактности модуля
> **Например**: `Card` и `UserCard` оба могут не коннектиться к стору, при этом UserCard более конкретный и часто изменяемый чем uikit-ный Card, т.к. еще добавляет специфику обработки данных в UI
 
Но если по абстрактности (~ степени ответственности) становится заметно, что компонент сильно отличается от других в этом слое, возможно как раз стоит его вынести в слой пониже/повыше
(смотря какие слои внедрены в проекте и готова ли к этому команда)

У components/containers [есть свои недостатки](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0) , но если хочется - можно использовать смело, если хотите с командой (методология это не регулирует, если это не противоречит общим концепциям слайсов/сегментов)

![image](https://user-images.githubusercontent.com/42924400/183857640-85cbc1b0-9abc-488d-821a-dcea753cfd36.png)
![image](https://user-images.githubusercontent.com/42924400/183857663-937a460b-12b5-484f-864d-b599359dd9d8.png)

**Comment by WoodenPC** [comment]
Спасибо) Вопрос закрыт
