### ISSUE TITLE
WEBSITE: 404 when looking for units

### ISSUE THREAD

**Issue by yesnoruly** [feature-sliced/documentation#598]
![image](https://github.com/feature-sliced/documentation/assets/64963734/049c7fdd-92c5-450f-bd15-0834bf2e6510)
![image](https://github.com/feature-sliced/documentation/assets/64963734/77a03b38-9575-4d2b-a06a-5fbbbb1a3791)

**Comment by azinit** [comment]
Hello! Thanks for issue, we'll try to resolve it asap ❤️

**Comment by illright** [comment]
Fixed (ish). Searching for segment names still won't yield a lot of value, but at least we now support searching in other languages and no longer have 404 as search results 🤡
