### ISSUE TITLE
Поправить в документации гайд Usage with NextJS

### ISSUE THREAD

**Issue by sultanbayev** [feature-sliced/documentation#714]
В английской версии документации заменить слово **app** на **pages**, как в русской версии.

![image](https://github.com/user-attachments/assets/0ee78685-8c2e-43b8-9632-ffb85ab94f38)

https://feature-sliced.design/docs/guides/tech/with-nextjs#renaming-the-pages-layer-within-the-fsd-structure

**Comment by illright** [comment]
Точно, спасибо за замечание!
